name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:4.3
        ports:
          - 5672:5672
    strategy:
      matrix:
        include:
          - pair:
              elixir: '1.14'
              otp: '26'
            lint: lint
          - pair:
              elixir: '1.18'
              otp: '27'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup elixir
        uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-

      - name: Install Mix dependencies
        run: mix deps.get

      - name: Check Formatting
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Run Credo
        run: mix credo --strict
        if: ${{ matrix.lint }}

      - name: Compile dependencies
        run: mix deps.compile -f

      - name: Compile Mix app
        run: mix compile -f

      - name: Run tests
        run: mix test.ci

