name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
    strategy:
      matrix:
        include:
          - pair:
              elixir: '1.11'
              otp: '23.0'
          - pair:
              elixir: '1.12'
              otp: '24.0'
            lint: lint
    steps:
      - uses: actions/checkout@v2

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-

      - name: Install Mix dependencies
        run: mix deps.get

      - name: Check Formatting
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Run Credo
        run: mix credo --strict
        if: ${{ matrix.lint }}

      - name: Compile dependencies
        run: mix deps.compile -f

      - name: Compile Mix app
        run: mix compile -f

      - name: Run tests
        run: mix test.ci

